name: Lint
on:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: python -m pip install uv
        
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
            uv sync
      - name: Lint with Ruff
        run: uv run ruff --output-format=github .